rule M_Methodology_HTTP_SerializedObject_JNDIObj_dns_raw {
	meta:
		author="Auto-generated by heyserial.py - Alyssa Rahman (@ramen0x3f)"
		description="Auto-generated rule for serialized objects with the keyword/chain: dns"
	strings:
		$objheader={24 7b 6a 6e 64 69 3a}
		$keyword0 = { 64 6e 73 3a 2f}
	condition:
		$objheader and (@keyword0[1] > @objheader[1])
}
rule M_Methodology_HTTP_SerializedObject_JNDIObj_dns_base64 {
	meta:
		author="Auto-generated by heyserial.py - Alyssa Rahman (@ramen0x3f)"
		description="Auto-generated rule for serialized objects with the keyword/chain: dns"
	strings:
		$objheader="JHtqbmRpO"
		$keyword0 = /(ZG5zOi|Ruczov|kbnM6L)/
	condition:
		$objheader and (@keyword0[1] > @objheader[1])
}
rule M_Methodology_HTTP_SerializedObject_JNDIObj_dns_base64base64 {
	meta:
		author="Auto-generated by heyserial.py - Alyssa Rahman (@ramen0x3f)"
		description="Auto-generated rule for serialized objects with the keyword/chain: dns"
	strings:
		$objheader={53 6b 68 30 63 57 4a 74 55 6e 42 50}
		$keyword0 = /(\x57\x6b\x63\x31\x65\x6b\x39\x70|\x70\x48\x4e\x58\x70\x50\x61|\x61\x52\x7a\x56\x36\x54\x32|\x55\x6e\x56\x6a\x65\x6d\x39\x32|\x4a\x31\x59\x33\x70\x76\x64|\x53\x64\x57\x4e\x36\x62\x33|\x61\x32\x4a\x75\x54\x54\x5a\x4d|\x74\x69\x62\x6b\x30\x32\x54|\x72\x59\x6d\x35\x4e\x4e\x6b)/
	condition:
		$objheader and (@keyword0[1] > @objheader[1])
}
