rule M_Methodology_HTTP_SerializedObject_JNDIObj_rmi_raw {
	meta:
		author="Auto-generated by heyserial.py - Alyssa Rahman (@ramen0x3f)"
		description="Auto-generated rule for serialized objects with the keyword/chain: rmi"
	strings:
		$objheader={24 7b 6a 6e 64 69 3a}
		$keyword0 = { 72 6d 69 3a 2f}
	condition:
		$objheader and (@keyword0[1] > @objheader[1])
}
rule M_Methodology_HTTP_SerializedObject_JNDIObj_rmi_base64 {
	meta:
		author="Auto-generated by heyserial.py - Alyssa Rahman (@ramen0x3f)"
		description="Auto-generated rule for serialized objects with the keyword/chain: rmi"
	strings:
		$objheader="JHtqbmRpO"
		$keyword0 = /(cm1pOi|JtaTov|ybWk6L)/
	condition:
		$objheader and (@keyword0[1] > @objheader[1])
}
rule M_Methodology_HTTP_SerializedObject_JNDIObj_rmi_base64base64 {
	meta:
		author="Auto-generated by heyserial.py - Alyssa Rahman (@ramen0x3f)"
		description="Auto-generated rule for serialized objects with the keyword/chain: rmi"
	strings:
		$objheader={53 6b 68 30 63 57 4a 74 55 6e 42 50}
		$keyword0 = /(\x59\x32\x30\x78\x63\x45\x39\x70|\x4e\x74\x4d\x58\x42\x50\x61|\x6a\x62\x54\x46\x77\x54\x32|\x53\x6e\x52\x68\x56\x47\x39\x32|\x70\x30\x59\x56\x52\x76\x64|\x4b\x64\x47\x46\x55\x62\x33|\x65\x57\x4a\x58\x61\x7a\x5a\x4d|\x6c\x69\x56\x32\x73\x32\x54|\x35\x59\x6c\x64\x72\x4e\x6b)/
	condition:
		$objheader and (@keyword0[1] > @objheader[1])
}
